# Generated by Django 4.2.3 on 2023-07-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_contact_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact", name="desc", field=models.TextField(max_length=5000),
        ),
    ]
