# Generated by Django 4.2.3 on 2023-07-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_contact_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact", name="date", field=models.DateTimeField(),
        ),
    ]
